#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=padfone
MANUFACTURER=asus

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/bin/ATFWD-daemon ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/ATFWD-daemon
adb pull /system/bin/bridgemgrd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bridgemgrd
adb pull /system/bin/btnvtool ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/btnvtool
adb pull /system/bin/diag_mdlog ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/diag_mdlog
adb pull /system/bin/ds_fmc_appd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/ds_fmc_appd
adb pull /system/bin/efsks ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/efsks
adb pull /system/bin/hci_qcomm_init ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/hci_qcomm_init
adb pull /system/bin/ks ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/ks
adb pull /system/bin/mm-qcamera-daemon ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/mm-qcamera-daemon
adb pull /system/bin/mpdecision ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/mpdecision
adb pull /system/bin/netmgrd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/netmgrd
adb pull /system/bin/nl_listener ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/nl_listener
adb pull /system/bin/port-bridge ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/port-bridge
adb pull /system/bin/qcks ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/qcks
adb pull /system/bin/qmuxd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/qmuxd
adb pull /system/bin/qseecomd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/qseecomd
adb pull /system/bin/radish ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/radish
adb pull /system/bin/rmt_storage ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rmt_storage	
adb pull /system/bin/thermald ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/thermald
adb pull /system/bin/usbhub ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/usbhub
adb pull /system/bin/usbhub_init ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/usbhub_init
adb pull /system/etc/apns-conf.xml ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/apns-conf.xml
adb pull /system/etc/firmware/tzapps.b00 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tzapps.b00
adb pull /system/etc/firmware/tzapps.b01 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tzapps.b01
adb pull /system/etc/firmware/tzapps.b02 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tzapps.b02
adb pull /system/etc/firmware/tzapps.b03 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tzapps.b03
adb pull /system/etc/firmware/tzapps.mdt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tzapps.mdt
adb pull /system/etc/firmware/vidc.b00 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/vidc.b00
adb pull /system/etc/firmware/vidc.b01 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/vidc.b01
adb pull /system/etc/firmware/vidc.b02 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/vidc.b02
adb pull /system/etc/firmware/vidc.b03 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/vidc.b03
adb pull /system/etc/firmware/vidc.mdt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/vidc.mdt
adb pull /system/etc/firmware/vidcfw.elf ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/vidcfw.elf
adb pull /system/etc/firmware/vidc_1080p.fw ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/vidc_1080p.fw
adb pull /system/etc/gps.conf ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/gps.conf
adb pull /system/lib/egl/eglsubAndroid.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/eglsubAndroid.so
adb pull /system/lib/egl/libEGL_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libEGL_adreno200.so
adb pull /system/lib/egl/libGLESv1_CM_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv1_CM_adreno200.so
adb pull /system/lib/egl/libGLESv2_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv2_adreno200.so
adb pull /system/lib/egl/libGLESv2S3D_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv2S3D_adreno200.so
adb pull /system/lib/egl/libq3dtools_adreno200.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libq3dtools_adreno200.so
adb pull /system/lib/hw/gps.default.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/gps.default.so
adb pull /system/lib/hw/sensors6050.qcom.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/sensors6050.qcom.so
adb pull /system/lib/hw/sensors.qcom.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/sensors.qcom.so
adb pull /system/lib/libacdbloader.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libacdbloader.so
adb pull /system/lib/libaudcal.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libaudcal.so
adb pull /system/lib/libaudioalsa.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libaudioalsa.so
adb pull /system/lib/libC2D2.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libC2D2.so
adb pull /system/lib/libc2d2_a3xx.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libc2d2_a3xx.so
adb pull /system/lib/libc2d2_z180.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libc2d2_z180.so
adb pull /system/lib/libchromatix_ov5647_default_video.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libchromatix_ov5647_default_video.so
adb pull /system/lib/libchromatix_ov5647_preview.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libchromatix_ov5647_preview.so
adb pull /system/lib/libchromatix_ov5647_video_hfr.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libchromatix_ov5647_video_hfr.so
adb pull /system/lib/libCommandSvc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libCommandSvc.so
adb pull /system/lib/libconfigdb.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libconfigdb.so
adb pull /system/lib/libcsd-client.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libcsd-client.so
adb pull /system/lib/libdiag.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libdiag.so
adb pull /system/lib/libdrmdiag.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libdrmdiag.so
adb pull /system/lib/libdrmfs.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libdrmfs.so
adb pull /system/lib/libdrmtime.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libdrmtime.so
adb pull /system/lib/libdsi_netctrl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libdsi_netctrl.so
adb pull /system/lib/libdsprofile.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libdsprofile.so
adb pull /system/lib/libdss.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libdss.so
adb pull /system/lib/libdsucsd.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libdsucsd.so
adb pull /system/lib/libdsutils.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libdsutils.so
adb pull /system/lib/libgps.utils.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libgps.utils.so
adb pull /system/lib/libgsl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libgsl.so
adb pull /system/lib/libI420colorconvert.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libI420colorconvert.so
adb pull /system/lib/libidl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libidl.so
adb pull /system/lib/libllvm-a3xx.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libllvm-a3xx.so
adb pull /system/lib/libloc_eng.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libloc_eng.so
adb pull /system/lib/libmm-abl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmm-abl.so
adb pull /system/lib/libmm-color-convertor.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmm-color-convertor.so
adb pull /system/lib/libmmcamera_image_stab.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmmcamera_image_stab.so
adb pull /system/lib/libnetmgr.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libnetmgr.so
adb pull /system/lib/libqcci_legacy.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libqcci_legacy.so
adb pull /system/lib/libqdi.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libqdi.so
adb pull /system/lib/libqdp.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libqdp.so
adb pull /system/lib/libqmi.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libqmi.so
adb pull /system/lib/libqmi_cci.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libqmi_cci.so
adb pull /system/lib/libqmi_client_qmux.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libqmi_client_qmux.so
adb pull /system/lib/libqmi_common_so.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libqmi_common_so.so
adb pull /system/lib/libqmi_csi.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libqmi_csi.so
adb pull /system/lib/libqmi_csvt_srvc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libqmi_csvt_srvc.so
adb pull /system/lib/libqmi_encdec.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libqmi_encdec.so
adb pull /system/lib/libQSEEComAPI.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libQSEEComAPI.so
adb pull /system/lib/libril-qc-qmi-1.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libril-qc-qmi-1.so
adb pull /system/lib/libril-qcril-hook-oem.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libril-qcril-hook-oem.so
adb pull /system/lib/libsc-a3xx.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libsc-a3xx.so
adb pull /system/lib/libstagefright_omx.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libstagefright_omx.so
adb pull /system/lib/libxml.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libxml.so
adb pull /system/etc/firmware/a300_pfp.fw ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/a300_pfp.fw
adb pull /system/etc/firmware/a300_pm4.fw ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/a300_pm4.fw
adb pull /system/etc/firmware/dsps.b00 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/dsps.b00
adb pull /system/etc/firmware/dsps.b01 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/dsps.b01
adb pull /system/etc/firmware/dsps.b02 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/dsps.b02
adb pull /system/etc/firmware/dsps.b03 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/dsps.b03
adb pull /system/etc/firmware/dsps.b04 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/dsps.b04
adb pull /system/etc/firmware/dsps.b05 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/dsps.b05
adb pull /system/etc/firmware/dsps.mdt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/dsps.mdt
adb pull /system/etc/firmware/q6.b00 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/q6.b00
adb pull /system/etc/firmware/q6.b01 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/q6.b01
adb pull /system/etc/firmware/q6.b03 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/q6.b03
adb pull /system/etc/firmware/q6.b04 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/q6.b04
adb pull /system/etc/firmware/q6.b05 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/q6.b05
adb pull /system/etc/firmware/q6.b06 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/q6.b06
adb pull /system/etc/firmware/q6.mdt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/q6.mdt
adb pull /system/etc/firmware/tzapps.b00 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tzapps.b00
adb pull /system/etc/firmware/tzapps.b01 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tzapps.b01
adb pull /system/etc/firmware/tzapps.b02 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tzapps.b02
adb pull /system/etc/firmware/tzapps.b03 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tzapps.b03
adb pull /system/etc/firmware/tzapps.mdt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tzapps.mdt
adb pull /system/etc/firmware/wcnss.b00 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wcnss.b00
adb pull /system/etc/firmware/wcnss.b01 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wcnss.b01
adb pull /system/etc/firmware/wcnss.b02 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wcnss.b02
adb pull /system/etc/firmware/wcnss.b04 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wcnss.b04
adb pull /system/etc/firmware/wcnss.mdt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wcnss.mdt
adb pull /system/lib/libgemini.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libgemini.so
adb pull /system/lib/libimage-jpeg-enc-omx-comp.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libimage-jpeg-enc-omx-comp.so
adb pull /system/lib/libimage-omx-common.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libimage-omx-common.so
adb pull /system/lib/libloc_api_v02.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libloc_api_v02.so
adb pull /system/lib/libmmcamera_faceproc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmmcamera_faceproc.so
adb pull /system/lib/libmmipl.so	../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmmipl.so
adb pull /system/lib/libmmjpeg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmmjpeg.so
adb pull /system/lib/libmmstillomx.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmmstillomx.so
adb pull /system/lib/liboemcamera.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/liboemcamera.so

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/bridgemgrd:system/bin/bridgemgrd

# All the blobs necessary for torospr
PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/btnvtool:system/bin/btnvtool \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/diag_mdlog:system/bin/diag_mdlog \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/ds_fmc_appd system/bin/ds_fmc_appd \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/efsks:system/bin/efsks \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/hci_qcomm_init:system/bin/hci_qcomm_init \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/ks:system/bin/ks \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/mpdecision:system/bin/mpdecision \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/netmgrd:system/bin/netmgrd \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/nl_listener:system/bin/nl_listener \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/port-bridge:system/bin/port-bridge \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/qcks:system/bin/qcks \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/qmuxd:system/bin/qmuxd \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/qseecomd:system/bin/qseecomd \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/radish:system/bin/radish \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rmt_storage:system/bin/rmt_storage \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/thermald:system/bin/thermald \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/usbhub:system/bin/usbhub \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/usbhub_init:system/bin/usbhub_init \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/apns-conf.xml:system/etc/apns-conf.xml \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tzapps.b00:system/etc/firmware/tzapps.b00 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tzapps.b01:system/etc/firmware/tzapps.b01 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tzapps.b02:system/etc/firmware/tzapps.b02 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tzapps.b03:system/etc/firmware/tzapps.b03 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tzapps.mdt:system/etc/firmware/tzapps.mdt \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/vidc.b00:system/etc/firmware/vidc.b00 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/vidc.b01:system/etc/firmware/vidc.b01 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/vidc.b02:system/etc/firmware/vidc.b02 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/vidc.b03:system/etc/firmware/vidc.b03 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/vidc.mdt:system/etc/firmware/vidc.mdt \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/vidcfw.elf:system/etc/firmware/vidcfw.elf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gps.conf:system/etc/gps.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gps.msm8960.so:system/lib/hw/gps.msm8960.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/sensors6050.qcom.so:system/lib/hw/sensors6050.qcom.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/sensors.qcom.so:system/lib/hw/sensors.qcom.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libacdbloader.so:system/lib/libacdbloader.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudcal.so:system/lib/libaudcal.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudioalsa.so:system/lib/libaudioalsa.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libC2D2.so:system/lib/libC2D2.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libc2d2_z180.so:system/lib/libc2d2_z180.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libchromatix_ov5647_video_hfr.so:system/lib/libchromatix_ov5647_hfr.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libCommandSvc.so:system/lib/libCommandSvc.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libconfigdb.so:system/lib/libconfigdb.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcsd-client.so:system/lib/libcsd-client.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdiag.so:system/lib/libdiag.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdrmdiag.so:system/lib/libdrmdiag.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdrmfs.so:system/lib/libdrmfs.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdrmtime.so:system/lib/libdrmtime.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdsprofile.so:system/lib/libdsprofile.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdss.so:system/lib/libdss.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdsucsd.so:system/lib/libdsucsd.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdsutils.so:system/lib/libdsutils.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libgps.utils.so:system/lib/libgps.utils.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libgsl.so:system/lib/libgsl.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libI420colorconvert.so:system/lib/libI420colorconvert.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libidl.so:system/lib/libidl.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libloc_eng.so:system/lib/libloc_eng.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmm-abl.so:system/lib/libmm-abl.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libnetmgr.so:system/lib/libnetmgr.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqcci_legacy.so:system/lib/libqcci_legacy.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqdi.so:system/lib/libqdi.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqdp.so:system/lib/libqdp.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqmi.so:system/lib/libqmi.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqmi_cci.so:system/lib/libqmi_cci.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqmi_common_so.so:system/lib/libqmi_common_so.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqmi_csi.so:system/lib/libqmi_csi.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libqmi_encdec.so:system/lib/libqmi_encdec.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libsc-a3xx.so:system/lib/libsc-a3xx.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libstagefright_omx.so:system/lib/libstagefright_omx.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libxml.so:system/lib/libxml.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/dsps.b00:system/etc/firmware/dsps.b00 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/dsps.b01:system/etc/firmware/dsps.b01 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/dsps.b02:system/etc/firmware/dsps.b02 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/dsps.b03:system/etc/firmware/dsps.b03 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/dsps.b04:system/etc/firmware/dsps.b04 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/dsps.b05:system/etc/firmware/dsps.b05 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/dsps.mdt:system/etc/firmware/dsps.mdt \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/q6.b00:system/etc/firmware/q6.b00 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/q6.b01:system/etc/firmware/q6.b01 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/q6.b03:system/etc/firmware/q6.b03 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/q6.b04:system/etc/firmware/q6.b04 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/q6.b05:system/etc/firmware/q6.b05 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/q6.b06:system/etc/firmware/q6.b06 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/q6.mdt:system/etc/firmware/q6.mdt \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tzapps.b00:system/etc/firmware/tzapps.b00 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tzapps.b01:system/etc/firmware/tzapps.b01 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tzapps.b02:system/etc/firmware/tzapps.b02 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tzapps.b03:system/etc/firmware/tzapps.b03 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tzapps.mdt:system/etc/firmware/tzapps.mdt \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wcnss.b00:system/etc/firmware/wcnss.b00 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wcnss.b01:system/etc/firmware/wcnss.b01 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wcnss.b02:system/etc/firmware/wcnss.b02 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wcnss.b04:system/etc/firmware/wcnss.b04 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wcnss.b05:system/etc/firmware/wcnss.b05 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wcnss.mdt:system/etc/firmware/wcnss.mdt \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libgemini.so:system/lib/libgemini.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libimage-omx-common.so:system/lib/libimage-omx-common.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libloc_api_v02.so:system/lib/libloc_api_v02.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmmipl.so:system/lib/libmmipl.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmmstillomx.so:system/lib/libmmstillomx.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/liboemcamera.so:system/lib/liboemcamera.so

EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/Android.mk
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

ifeq (\$(TARGET_DEVICE),padfone)
LOCAL_PATH:=\$(call my-dir)

endif


EOF

./setup-makefiles.sh
